import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PopupProvider } from "@/components/Common/Popup/PopupContext";
import Header from "@/components/Header/Header/Header";
import AuthHydrator from "./_providers/AuthHydrator";
import BottomNavBarGate from "@/components/_components/BottomNavBarGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthHydrator />
      <PopupProvider>
         <Header />
         <main className="container mt-4 nav-footer-spacing">
            {children}
          </main>
          <BottomNavBarGate />
        </PopupProvider>
      </body>
    </html>
  );
}
